### ISSUE TITLE
Fast and Flexible Convolutional Sparse Coding

### ISSUE THREAD

**Issue by zy-zy-coder** [PC91/ConvolutionalSparseCoding#2]
Hello, seeing that you have reproduced the code of this paper, could you help me to see how this formula is derived? I have been pushing it for a few days. Thank you very much!
dopt = (Z†Z + 2I)−1(Z†τ1 + τ2 + τ3) for y = d
zopt = (D†D + I)−1(D†τ1 + τ2) for y = z

**Comment by PC91** [comment]
Hi,
Sorry for my late response. Actually in this repository, I only translated the code from the paper (written in Matlab) for the case of image and then simplified in to adapt to signals. I did not delve into details about how the formulas are derived.
